server:
  port: 8888
spring:
  application:
    name: remoteconfigserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: git@github.com:***/***.git #git仓库地址
          searchPaths: remoteRepositoryConfig #仓库路径
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/