server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    name: online_ordering_platform
    url: jdbc:mysql://localhost:3306/online_ordering_platform?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.minichn.entity